-- Same-organization foreign keys (generated by packages/db/scripts/generate-same-org-triggers.ts)
CREATE OR REPLACE FUNCTION crm_assert_same_org() RETURNS trigger AS $$
DECLARE
  fk_col text := TG_ARGV[0];
  parent_table text := TG_ARGV[1];
  parent_col text := TG_ARGV[2];
  fk_val text;
  parent_org text;
BEGIN
  EXECUTE format('SELECT ($1).%I::text', fk_col) INTO fk_val USING NEW;
  IF fk_val IS NULL THEN
    RETURN NEW;
  END IF;
  EXECUTE format('SELECT "organizationId" FROM %I WHERE %I = $1', parent_table, parent_col) INTO parent_org USING fk_val;
  IF parent_org IS NULL OR parent_org <> NEW."organizationId" THEN
    RAISE EXCEPTION 'cross-tenant reference: %.% = % belongs to organization % (row is in %)',
      TG_TABLE_NAME, fk_col, fk_val, COALESCE(parent_org, '<missing>'), NEW."organizationId"
      USING ERRCODE = '23503';
  END IF;
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

-- A tenant row never changes organization.
CREATE OR REPLACE FUNCTION crm_org_immutable() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'organizationId is immutable: %.% cannot move from % to %',
    TG_TABLE_NAME, 'organizationId', OLD."organizationId", NEW."organizationId"
    USING ERRCODE = '23514';
END
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS "activity_org_immutable" ON "activity";
CREATE TRIGGER "activity_org_immutable" BEFORE UPDATE OF "organizationId" ON "activity"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentAction_org_immutable" ON "agentAction";
CREATE TRIGGER "agentAction_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentAction"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentAuditEvent_org_immutable" ON "agentAuditEvent";
CREATE TRIGGER "agentAuditEvent_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentAuditEvent"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentBuilderArtifact_org_immutable" ON "agentBuilderArtifact";
CREATE TRIGGER "agentBuilderArtifact_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentBuilderArtifact"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentConversation_org_immutable" ON "agentConversation";
CREATE TRIGGER "agentConversation_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentConversation"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentConversationAttachment_org_immutable" ON "agentConversationAttachment";
CREATE TRIGGER "agentConversationAttachment_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentConversationAttachment"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentConversationFeedback_org_immutable" ON "agentConversationFeedback";
CREATE TRIGGER "agentConversationFeedback_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentConversationFeedback"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentConversationShare_org_immutable" ON "agentConversationShare";
CREATE TRIGGER "agentConversationShare_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentConversationShare"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentConversationSubmission_org_immutable" ON "agentConversationSubmission";
CREATE TRIGGER "agentConversationSubmission_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentConversationSubmission"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentDefinition_org_immutable" ON "agentDefinition";
CREATE TRIGGER "agentDefinition_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentDefinition"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentEvent_org_immutable" ON "agentEvent";
CREATE TRIGGER "agentEvent_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentEvent"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentRun_org_immutable" ON "agentRun";
CREATE TRIGGER "agentRun_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentRun"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentRunEvent_org_immutable" ON "agentRunEvent";
CREATE TRIGGER "agentRunEvent_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentRunEvent"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentTask_org_immutable" ON "agentTask";
CREATE TRIGGER "agentTask_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentTask"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentTrigger_org_immutable" ON "agentTrigger";
CREATE TRIGGER "agentTrigger_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentTrigger"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "agentVersion_org_immutable" ON "agentVersion";
CREATE TRIGGER "agentVersion_org_immutable" BEFORE UPDATE OF "organizationId" ON "agentVersion"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "appSetting_org_immutable" ON "appSetting";
CREATE TRIGGER "appSetting_org_immutable" BEFORE UPDATE OF "organizationId" ON "appSetting"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "auditEvent_org_immutable" ON "auditEvent";
CREATE TRIGGER "auditEvent_org_immutable" BEFORE UPDATE OF "organizationId" ON "auditEvent"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "calendarAttendee_org_immutable" ON "calendarAttendee";
CREATE TRIGGER "calendarAttendee_org_immutable" BEFORE UPDATE OF "organizationId" ON "calendarAttendee"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "calendarEvent_org_immutable" ON "calendarEvent";
CREATE TRIGGER "calendarEvent_org_immutable" BEFORE UPDATE OF "organizationId" ON "calendarEvent"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "company_org_immutable" ON "company";
CREATE TRIGGER "company_org_immutable" BEFORE UPDATE OF "organizationId" ON "company"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "companyEnrichment_org_immutable" ON "companyEnrichment";
CREATE TRIGGER "companyEnrichment_org_immutable" BEFORE UPDATE OF "organizationId" ON "companyEnrichment"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "contact_org_immutable" ON "contact";
CREATE TRIGGER "contact_org_immutable" BEFORE UPDATE OF "organizationId" ON "contact"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "contactBrief_org_immutable" ON "contactBrief";
CREATE TRIGGER "contactBrief_org_immutable" BEFORE UPDATE OF "organizationId" ON "contactBrief"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "contactFact_org_immutable" ON "contactFact";
CREATE TRIGGER "contactFact_org_immutable" BEFORE UPDATE OF "organizationId" ON "contactFact"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "deal_org_immutable" ON "deal";
CREATE TRIGGER "deal_org_immutable" BEFORE UPDATE OF "organizationId" ON "deal"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "dealContact_org_immutable" ON "dealContact";
CREATE TRIGGER "dealContact_org_immutable" BEFORE UPDATE OF "organizationId" ON "dealContact"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "emailMessage_org_immutable" ON "emailMessage";
CREATE TRIGGER "emailMessage_org_immutable" BEFORE UPDATE OF "organizationId" ON "emailMessage"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "emailThread_org_immutable" ON "emailThread";
CREATE TRIGGER "emailThread_org_immutable" BEFORE UPDATE OF "organizationId" ON "emailThread"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "fieldDefinition_org_immutable" ON "fieldDefinition";
CREATE TRIGGER "fieldDefinition_org_immutable" BEFORE UPDATE OF "organizationId" ON "fieldDefinition"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "fieldOption_org_immutable" ON "fieldOption";
CREATE TRIGGER "fieldOption_org_immutable" BEFORE UPDATE OF "organizationId" ON "fieldOption"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "fieldValue_org_immutable" ON "fieldValue";
CREATE TRIGGER "fieldValue_org_immutable" BEFORE UPDATE OF "organizationId" ON "fieldValue"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "formSubmission_org_immutable" ON "formSubmission";
CREATE TRIGGER "formSubmission_org_immutable" BEFORE UPDATE OF "organizationId" ON "formSubmission"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "mailboxSync_org_immutable" ON "mailboxSync";
CREATE TRIGGER "mailboxSync_org_immutable" BEFORE UPDATE OF "organizationId" ON "mailboxSync"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "slackChannel_org_immutable" ON "slackChannel";
CREATE TRIGGER "slackChannel_org_immutable" BEFORE UPDATE OF "organizationId" ON "slackChannel"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "slackInstallation_org_immutable" ON "slackInstallation";
CREATE TRIGGER "slackInstallation_org_immutable" BEFORE UPDATE OF "organizationId" ON "slackInstallation"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "slackMemberMatch_org_immutable" ON "slackMemberMatch";
CREATE TRIGGER "slackMemberMatch_org_immutable" BEFORE UPDATE OF "organizationId" ON "slackMemberMatch"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "slackWorkspaceGrant_org_immutable" ON "slackWorkspaceGrant";
CREATE TRIGGER "slackWorkspaceGrant_org_immutable" BEFORE UPDATE OF "organizationId" ON "slackWorkspaceGrant"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "suppressedContact_org_immutable" ON "suppressedContact";
CREATE TRIGGER "suppressedContact_org_immutable" BEFORE UPDATE OF "organizationId" ON "suppressedContact"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "suppressedDomain_org_immutable" ON "suppressedDomain";
CREATE TRIGGER "suppressedDomain_org_immutable" BEFORE UPDATE OF "organizationId" ON "suppressedDomain"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "trackedDomain_org_immutable" ON "trackedDomain";
CREATE TRIGGER "trackedDomain_org_immutable" BEFORE UPDATE OF "organizationId" ON "trackedDomain"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "trackedEvent_org_immutable" ON "trackedEvent";
CREATE TRIGGER "trackedEvent_org_immutable" BEFORE UPDATE OF "organizationId" ON "trackedEvent"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "trackedPageDaily_org_immutable" ON "trackedPageDaily";
CREATE TRIGGER "trackedPageDaily_org_immutable" BEFORE UPDATE OF "organizationId" ON "trackedPageDaily"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "trackedVisitor_org_immutable" ON "trackedVisitor";
CREATE TRIGGER "trackedVisitor_org_immutable" BEFORE UPDATE OF "organizationId" ON "trackedVisitor"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "trackingCounter_org_immutable" ON "trackingCounter";
CREATE TRIGGER "trackingCounter_org_immutable" BEFORE UPDATE OF "organizationId" ON "trackingCounter"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "workspaceProfile_org_immutable" ON "workspaceProfile";
CREATE TRIGGER "workspaceProfile_org_immutable" BEFORE UPDATE OF "organizationId" ON "workspaceProfile"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();
DROP TRIGGER IF EXISTS "company_primaryContactId_same_org" ON "company";
CREATE TRIGGER "company_primaryContactId_same_org" BEFORE INSERT OR UPDATE OF "primaryContactId", "organizationId" ON "company"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('primaryContactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "companyEnrichment_companyId_same_org" ON "companyEnrichment";
CREATE TRIGGER "companyEnrichment_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "companyEnrichment"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "contact_companyId_same_org" ON "contact";
CREATE TRIGGER "contact_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "contact"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "contactFact_contactId_same_org" ON "contactFact";
CREATE TRIGGER "contactFact_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "contactFact"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "contactBrief_contactId_same_org" ON "contactBrief";
CREATE TRIGGER "contactBrief_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "contactBrief"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "agentEvent_conversationId_same_org" ON "agentEvent";
CREATE TRIGGER "agentEvent_conversationId_same_org" BEFORE INSERT OR UPDATE OF "conversationId", "organizationId" ON "agentEvent"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('conversationId', 'agentConversation', 'id');
DROP TRIGGER IF EXISTS "agentConversation_contactId_same_org" ON "agentConversation";
CREATE TRIGGER "agentConversation_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "agentConversation"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "agentConversation_companyId_same_org" ON "agentConversation";
CREATE TRIGGER "agentConversation_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "agentConversation"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "agentConversation_dealId_same_org" ON "agentConversation";
CREATE TRIGGER "agentConversation_dealId_same_org" BEFORE INSERT OR UPDATE OF "dealId", "organizationId" ON "agentConversation"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('dealId', 'deal', 'id');
DROP TRIGGER IF EXISTS "agentConversation_agentId_same_org" ON "agentConversation";
CREATE TRIGGER "agentConversation_agentId_same_org" BEFORE INSERT OR UPDATE OF "agentId", "organizationId" ON "agentConversation"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('agentId', 'agentDefinition', 'id');
DROP TRIGGER IF EXISTS "agentConversationFeedback_conversationId_same_org" ON "agentConversationFeedback";
CREATE TRIGGER "agentConversationFeedback_conversationId_same_org" BEFORE INSERT OR UPDATE OF "conversationId", "organizationId" ON "agentConversationFeedback"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('conversationId', 'agentConversation', 'id');
DROP TRIGGER IF EXISTS "agentConversationShare_conversationId_same_org" ON "agentConversationShare";
CREATE TRIGGER "agentConversationShare_conversationId_same_org" BEFORE INSERT OR UPDATE OF "conversationId", "organizationId" ON "agentConversationShare"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('conversationId', 'agentConversation', 'id');
DROP TRIGGER IF EXISTS "agentConversationSubmission_conversationId_same_org" ON "agentConversationSubmission";
CREATE TRIGGER "agentConversationSubmission_conversationId_same_org" BEFORE INSERT OR UPDATE OF "conversationId", "organizationId" ON "agentConversationSubmission"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('conversationId', 'agentConversation', 'id');
DROP TRIGGER IF EXISTS "agentConversationAttachment_submissionId_same_org" ON "agentConversationAttachment";
CREATE TRIGGER "agentConversationAttachment_submissionId_same_org" BEFORE INSERT OR UPDATE OF "submissionId", "organizationId" ON "agentConversationAttachment"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('submissionId', 'agentConversationSubmission', 'id');
DROP TRIGGER IF EXISTS "agentVersion_agentId_same_org" ON "agentVersion";
CREATE TRIGGER "agentVersion_agentId_same_org" BEFORE INSERT OR UPDATE OF "agentId", "organizationId" ON "agentVersion"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('agentId', 'agentDefinition', 'id');
DROP TRIGGER IF EXISTS "agentVersion_sourceConversationId_same_org" ON "agentVersion";
CREATE TRIGGER "agentVersion_sourceConversationId_same_org" BEFORE INSERT OR UPDATE OF "sourceConversationId", "organizationId" ON "agentVersion"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('sourceConversationId', 'agentConversation', 'id');
DROP TRIGGER IF EXISTS "agentBuilderArtifact_conversationId_same_org" ON "agentBuilderArtifact";
CREATE TRIGGER "agentBuilderArtifact_conversationId_same_org" BEFORE INSERT OR UPDATE OF "conversationId", "organizationId" ON "agentBuilderArtifact"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('conversationId', 'agentConversation', 'id');
DROP TRIGGER IF EXISTS "agentBuilderArtifact_versionId_same_org" ON "agentBuilderArtifact";
CREATE TRIGGER "agentBuilderArtifact_versionId_same_org" BEFORE INSERT OR UPDATE OF "versionId", "organizationId" ON "agentBuilderArtifact"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('versionId', 'agentVersion', 'id');
DROP TRIGGER IF EXISTS "agentTrigger_agentId_same_org" ON "agentTrigger";
CREATE TRIGGER "agentTrigger_agentId_same_org" BEFORE INSERT OR UPDATE OF "agentId", "organizationId" ON "agentTrigger"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('agentId', 'agentDefinition', 'id');
DROP TRIGGER IF EXISTS "agentRun_agentId_same_org" ON "agentRun";
CREATE TRIGGER "agentRun_agentId_same_org" BEFORE INSERT OR UPDATE OF "agentId", "organizationId" ON "agentRun"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('agentId', 'agentDefinition', 'id');
DROP TRIGGER IF EXISTS "agentRunEvent_runId_same_org" ON "agentRunEvent";
CREATE TRIGGER "agentRunEvent_runId_same_org" BEFORE INSERT OR UPDATE OF "runId", "organizationId" ON "agentRunEvent"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('runId', 'agentRun', 'id');
DROP TRIGGER IF EXISTS "agentAction_agentId_same_org" ON "agentAction";
CREATE TRIGGER "agentAction_agentId_same_org" BEFORE INSERT OR UPDATE OF "agentId", "organizationId" ON "agentAction"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('agentId', 'agentDefinition', 'id');
DROP TRIGGER IF EXISTS "agentAuditEvent_agentId_same_org" ON "agentAuditEvent";
CREATE TRIGGER "agentAuditEvent_agentId_same_org" BEFORE INSERT OR UPDATE OF "agentId", "organizationId" ON "agentAuditEvent"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('agentId', 'agentDefinition', 'id');
DROP TRIGGER IF EXISTS "deal_companyId_same_org" ON "deal";
CREATE TRIGGER "deal_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "deal"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "dealContact_dealId_same_org" ON "dealContact";
CREATE TRIGGER "dealContact_dealId_same_org" BEFORE INSERT OR UPDATE OF "dealId", "organizationId" ON "dealContact"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('dealId', 'deal', 'id');
DROP TRIGGER IF EXISTS "dealContact_contactId_same_org" ON "dealContact";
CREATE TRIGGER "dealContact_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "dealContact"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "fieldOption_fieldId_same_org" ON "fieldOption";
CREATE TRIGGER "fieldOption_fieldId_same_org" BEFORE INSERT OR UPDATE OF "fieldId", "organizationId" ON "fieldOption"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('fieldId', 'fieldDefinition', 'id');
DROP TRIGGER IF EXISTS "fieldValue_fieldId_same_org" ON "fieldValue";
CREATE TRIGGER "fieldValue_fieldId_same_org" BEFORE INSERT OR UPDATE OF "fieldId", "organizationId" ON "fieldValue"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('fieldId', 'fieldDefinition', 'id');
DROP TRIGGER IF EXISTS "fieldValue_companyId_same_org" ON "fieldValue";
CREATE TRIGGER "fieldValue_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "fieldValue"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "fieldValue_contactId_same_org" ON "fieldValue";
CREATE TRIGGER "fieldValue_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "fieldValue"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "fieldValue_dealId_same_org" ON "fieldValue";
CREATE TRIGGER "fieldValue_dealId_same_org" BEFORE INSERT OR UPDATE OF "dealId", "organizationId" ON "fieldValue"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('dealId', 'deal', 'id');
DROP TRIGGER IF EXISTS "fieldValue_optionId_same_org" ON "fieldValue";
CREATE TRIGGER "fieldValue_optionId_same_org" BEFORE INSERT OR UPDATE OF "optionId", "organizationId" ON "fieldValue"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('optionId', 'fieldOption', 'id');
DROP TRIGGER IF EXISTS "activity_companyId_same_org" ON "activity";
CREATE TRIGGER "activity_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "activity"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "activity_contactId_same_org" ON "activity";
CREATE TRIGGER "activity_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "activity"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "activity_dealId_same_org" ON "activity";
CREATE TRIGGER "activity_dealId_same_org" BEFORE INSERT OR UPDATE OF "dealId", "organizationId" ON "activity"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('dealId', 'deal', 'id');
DROP TRIGGER IF EXISTS "activity_emailThreadId_same_org" ON "activity";
CREATE TRIGGER "activity_emailThreadId_same_org" BEFORE INSERT OR UPDATE OF "emailThreadId", "organizationId" ON "activity"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('emailThreadId', 'emailThread', 'id');
DROP TRIGGER IF EXISTS "activity_calendarEventId_same_org" ON "activity";
CREATE TRIGGER "activity_calendarEventId_same_org" BEFORE INSERT OR UPDATE OF "calendarEventId", "organizationId" ON "activity"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('calendarEventId', 'calendarEvent', 'id');
DROP TRIGGER IF EXISTS "emailThread_companyId_same_org" ON "emailThread";
CREATE TRIGGER "emailThread_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "emailThread"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "emailThread_contactId_same_org" ON "emailThread";
CREATE TRIGGER "emailThread_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "emailThread"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "emailMessage_threadId_same_org" ON "emailMessage";
CREATE TRIGGER "emailMessage_threadId_same_org" BEFORE INSERT OR UPDATE OF "threadId", "organizationId" ON "emailMessage"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('threadId', 'emailThread', 'id');
DROP TRIGGER IF EXISTS "calendarEvent_companyId_same_org" ON "calendarEvent";
CREATE TRIGGER "calendarEvent_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "calendarEvent"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "calendarEvent_contactId_same_org" ON "calendarEvent";
CREATE TRIGGER "calendarEvent_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "calendarEvent"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "calendarAttendee_eventId_same_org" ON "calendarAttendee";
CREATE TRIGGER "calendarAttendee_eventId_same_org" BEFORE INSERT OR UPDATE OF "eventId", "organizationId" ON "calendarAttendee"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('eventId', 'calendarEvent', 'id');
DROP TRIGGER IF EXISTS "calendarAttendee_contactId_same_org" ON "calendarAttendee";
CREATE TRIGGER "calendarAttendee_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "calendarAttendee"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "trackedVisitor_contactId_same_org" ON "trackedVisitor";
CREATE TRIGGER "trackedVisitor_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "trackedVisitor"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "formSubmission_contactId_same_org" ON "formSubmission";
CREATE TRIGGER "formSubmission_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "formSubmission"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
-- 46 tenant→tenant foreign keys guarded; organizationId immutable on 46 tables
