-- Same-organization foreign keys (generated by packages/db/scripts/generate-same-org-triggers.ts)
CREATE OR REPLACE FUNCTION crm_assert_same_org() RETURNS trigger AS $$
DECLARE
  fk_col text := TG_ARGV[0];
  parent_table text := TG_ARGV[1];
  parent_col text := TG_ARGV[2];
  fk_val text;
  parent_org text;
BEGIN
  EXECUTE format('SELECT ($1).%I::text', fk_col) INTO fk_val USING NEW;
  IF fk_val IS NULL THEN
    RETURN NEW;
  END IF;
  EXECUTE format('SELECT "organizationId" FROM %I WHERE %I = $1', parent_table, parent_col) INTO parent_org USING fk_val;
  IF parent_org IS NULL OR parent_org <> NEW."organizationId" THEN
    RAISE EXCEPTION 'cross-tenant reference: %.% = % belongs to organization % (row is in %)',
      TG_TABLE_NAME, fk_col, fk_val, COALESCE(parent_org, '<missing>'), NEW."organizationId"
      USING ERRCODE = '23503';
  END IF;
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS "company_primaryContactId_same_org" ON "company";
CREATE TRIGGER "company_primaryContactId_same_org" BEFORE INSERT OR UPDATE OF "primaryContactId", "organizationId" ON "company"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('primaryContactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "companyEnrichment_companyId_same_org" ON "companyEnrichment";
CREATE TRIGGER "companyEnrichment_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "companyEnrichment"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "contact_companyId_same_org" ON "contact";
CREATE TRIGGER "contact_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "contact"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "contactFact_contactId_same_org" ON "contactFact";
CREATE TRIGGER "contactFact_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "contactFact"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "contactBrief_contactId_same_org" ON "contactBrief";
CREATE TRIGGER "contactBrief_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "contactBrief"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "agentEvent_conversationId_same_org" ON "agentEvent";
CREATE TRIGGER "agentEvent_conversationId_same_org" BEFORE INSERT OR UPDATE OF "conversationId", "organizationId" ON "agentEvent"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('conversationId', 'agentConversation', 'id');
DROP TRIGGER IF EXISTS "agentConversation_contactId_same_org" ON "agentConversation";
CREATE TRIGGER "agentConversation_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "agentConversation"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "agentConversation_companyId_same_org" ON "agentConversation";
CREATE TRIGGER "agentConversation_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "agentConversation"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "agentConversation_dealId_same_org" ON "agentConversation";
CREATE TRIGGER "agentConversation_dealId_same_org" BEFORE INSERT OR UPDATE OF "dealId", "organizationId" ON "agentConversation"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('dealId', 'deal', 'id');
DROP TRIGGER IF EXISTS "agentConversation_agentId_same_org" ON "agentConversation";
CREATE TRIGGER "agentConversation_agentId_same_org" BEFORE INSERT OR UPDATE OF "agentId", "organizationId" ON "agentConversation"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('agentId', 'agentDefinition', 'id');
DROP TRIGGER IF EXISTS "agentConversationFeedback_conversationId_same_org" ON "agentConversationFeedback";
CREATE TRIGGER "agentConversationFeedback_conversationId_same_org" BEFORE INSERT OR UPDATE OF "conversationId", "organizationId" ON "agentConversationFeedback"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('conversationId', 'agentConversation', 'id');
DROP TRIGGER IF EXISTS "agentConversationShare_conversationId_same_org" ON "agentConversationShare";
CREATE TRIGGER "agentConversationShare_conversationId_same_org" BEFORE INSERT OR UPDATE OF "conversationId", "organizationId" ON "agentConversationShare"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('conversationId', 'agentConversation', 'id');
DROP TRIGGER IF EXISTS "agentConversationSubmission_conversationId_same_org" ON "agentConversationSubmission";
CREATE TRIGGER "agentConversationSubmission_conversationId_same_org" BEFORE INSERT OR UPDATE OF "conversationId", "organizationId" ON "agentConversationSubmission"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('conversationId', 'agentConversation', 'id');
DROP TRIGGER IF EXISTS "agentConversationAttachment_submissionId_same_org" ON "agentConversationAttachment";
CREATE TRIGGER "agentConversationAttachment_submissionId_same_org" BEFORE INSERT OR UPDATE OF "submissionId", "organizationId" ON "agentConversationAttachment"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('submissionId', 'agentConversationSubmission', 'id');
DROP TRIGGER IF EXISTS "agentVersion_agentId_same_org" ON "agentVersion";
CREATE TRIGGER "agentVersion_agentId_same_org" BEFORE INSERT OR UPDATE OF "agentId", "organizationId" ON "agentVersion"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('agentId', 'agentDefinition', 'id');
DROP TRIGGER IF EXISTS "agentVersion_sourceConversationId_same_org" ON "agentVersion";
CREATE TRIGGER "agentVersion_sourceConversationId_same_org" BEFORE INSERT OR UPDATE OF "sourceConversationId", "organizationId" ON "agentVersion"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('sourceConversationId', 'agentConversation', 'id');
DROP TRIGGER IF EXISTS "agentBuilderArtifact_conversationId_same_org" ON "agentBuilderArtifact";
CREATE TRIGGER "agentBuilderArtifact_conversationId_same_org" BEFORE INSERT OR UPDATE OF "conversationId", "organizationId" ON "agentBuilderArtifact"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('conversationId', 'agentConversation', 'id');
DROP TRIGGER IF EXISTS "agentBuilderArtifact_versionId_same_org" ON "agentBuilderArtifact";
CREATE TRIGGER "agentBuilderArtifact_versionId_same_org" BEFORE INSERT OR UPDATE OF "versionId", "organizationId" ON "agentBuilderArtifact"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('versionId', 'agentVersion', 'id');
DROP TRIGGER IF EXISTS "agentTrigger_agentId_same_org" ON "agentTrigger";
CREATE TRIGGER "agentTrigger_agentId_same_org" BEFORE INSERT OR UPDATE OF "agentId", "organizationId" ON "agentTrigger"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('agentId', 'agentDefinition', 'id');
DROP TRIGGER IF EXISTS "agentRun_agentId_same_org" ON "agentRun";
CREATE TRIGGER "agentRun_agentId_same_org" BEFORE INSERT OR UPDATE OF "agentId", "organizationId" ON "agentRun"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('agentId', 'agentDefinition', 'id');
DROP TRIGGER IF EXISTS "agentRunEvent_runId_same_org" ON "agentRunEvent";
CREATE TRIGGER "agentRunEvent_runId_same_org" BEFORE INSERT OR UPDATE OF "runId", "organizationId" ON "agentRunEvent"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('runId', 'agentRun', 'id');
DROP TRIGGER IF EXISTS "agentAction_agentId_same_org" ON "agentAction";
CREATE TRIGGER "agentAction_agentId_same_org" BEFORE INSERT OR UPDATE OF "agentId", "organizationId" ON "agentAction"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('agentId', 'agentDefinition', 'id');
DROP TRIGGER IF EXISTS "agentAuditEvent_agentId_same_org" ON "agentAuditEvent";
CREATE TRIGGER "agentAuditEvent_agentId_same_org" BEFORE INSERT OR UPDATE OF "agentId", "organizationId" ON "agentAuditEvent"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('agentId', 'agentDefinition', 'id');
DROP TRIGGER IF EXISTS "deal_companyId_same_org" ON "deal";
CREATE TRIGGER "deal_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "deal"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "dealContact_dealId_same_org" ON "dealContact";
CREATE TRIGGER "dealContact_dealId_same_org" BEFORE INSERT OR UPDATE OF "dealId", "organizationId" ON "dealContact"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('dealId', 'deal', 'id');
DROP TRIGGER IF EXISTS "dealContact_contactId_same_org" ON "dealContact";
CREATE TRIGGER "dealContact_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "dealContact"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "fieldOption_fieldId_same_org" ON "fieldOption";
CREATE TRIGGER "fieldOption_fieldId_same_org" BEFORE INSERT OR UPDATE OF "fieldId", "organizationId" ON "fieldOption"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('fieldId', 'fieldDefinition', 'id');
DROP TRIGGER IF EXISTS "fieldValue_fieldId_same_org" ON "fieldValue";
CREATE TRIGGER "fieldValue_fieldId_same_org" BEFORE INSERT OR UPDATE OF "fieldId", "organizationId" ON "fieldValue"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('fieldId', 'fieldDefinition', 'id');
DROP TRIGGER IF EXISTS "fieldValue_companyId_same_org" ON "fieldValue";
CREATE TRIGGER "fieldValue_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "fieldValue"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "fieldValue_contactId_same_org" ON "fieldValue";
CREATE TRIGGER "fieldValue_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "fieldValue"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "fieldValue_dealId_same_org" ON "fieldValue";
CREATE TRIGGER "fieldValue_dealId_same_org" BEFORE INSERT OR UPDATE OF "dealId", "organizationId" ON "fieldValue"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('dealId', 'deal', 'id');
DROP TRIGGER IF EXISTS "fieldValue_optionId_same_org" ON "fieldValue";
CREATE TRIGGER "fieldValue_optionId_same_org" BEFORE INSERT OR UPDATE OF "optionId", "organizationId" ON "fieldValue"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('optionId', 'fieldOption', 'id');
DROP TRIGGER IF EXISTS "activity_companyId_same_org" ON "activity";
CREATE TRIGGER "activity_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "activity"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "activity_contactId_same_org" ON "activity";
CREATE TRIGGER "activity_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "activity"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "activity_dealId_same_org" ON "activity";
CREATE TRIGGER "activity_dealId_same_org" BEFORE INSERT OR UPDATE OF "dealId", "organizationId" ON "activity"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('dealId', 'deal', 'id');
DROP TRIGGER IF EXISTS "activity_emailThreadId_same_org" ON "activity";
CREATE TRIGGER "activity_emailThreadId_same_org" BEFORE INSERT OR UPDATE OF "emailThreadId", "organizationId" ON "activity"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('emailThreadId', 'emailThread', 'id');
DROP TRIGGER IF EXISTS "activity_calendarEventId_same_org" ON "activity";
CREATE TRIGGER "activity_calendarEventId_same_org" BEFORE INSERT OR UPDATE OF "calendarEventId", "organizationId" ON "activity"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('calendarEventId', 'calendarEvent', 'id');
DROP TRIGGER IF EXISTS "emailThread_companyId_same_org" ON "emailThread";
CREATE TRIGGER "emailThread_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "emailThread"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "emailThread_contactId_same_org" ON "emailThread";
CREATE TRIGGER "emailThread_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "emailThread"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "emailMessage_threadId_same_org" ON "emailMessage";
CREATE TRIGGER "emailMessage_threadId_same_org" BEFORE INSERT OR UPDATE OF "threadId", "organizationId" ON "emailMessage"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('threadId', 'emailThread', 'id');
DROP TRIGGER IF EXISTS "calendarEvent_companyId_same_org" ON "calendarEvent";
CREATE TRIGGER "calendarEvent_companyId_same_org" BEFORE INSERT OR UPDATE OF "companyId", "organizationId" ON "calendarEvent"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('companyId', 'company', 'id');
DROP TRIGGER IF EXISTS "calendarEvent_contactId_same_org" ON "calendarEvent";
CREATE TRIGGER "calendarEvent_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "calendarEvent"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "calendarAttendee_eventId_same_org" ON "calendarAttendee";
CREATE TRIGGER "calendarAttendee_eventId_same_org" BEFORE INSERT OR UPDATE OF "eventId", "organizationId" ON "calendarAttendee"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('eventId', 'calendarEvent', 'id');
DROP TRIGGER IF EXISTS "calendarAttendee_contactId_same_org" ON "calendarAttendee";
CREATE TRIGGER "calendarAttendee_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "calendarAttendee"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "trackedVisitor_contactId_same_org" ON "trackedVisitor";
CREATE TRIGGER "trackedVisitor_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "trackedVisitor"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
DROP TRIGGER IF EXISTS "formSubmission_contactId_same_org" ON "formSubmission";
CREATE TRIGGER "formSubmission_contactId_same_org" BEFORE INSERT OR UPDATE OF "contactId", "organizationId" ON "formSubmission"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('contactId', 'contact', 'id');
-- 46 tenant→tenant foreign keys guarded
