/**
 * Emits SQL that makes Postgres refuse any row whose tenant-model foreign key
 * points at a row of another organization. This is the database-level backstop
 * behind the Prisma tenant extension: even a raw query, a bug, or an
 * attacker-supplied id cannot link rows across tenants.
 *
 * One generic trigger function + one BEFORE INSERT OR UPDATE trigger per
 * (child table, fk column) edge between tenant models. Regenerate whenever a
 * relation between tenant models is added: `bun scripts/generate-same-org-triggers.ts`
 * and put the output in a new migration.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { TENANT_MODELS } from "../src/tenant-map.generated";

const schema = readFileSync(
	join(import.meta.dir, "..", "prisma", "schema.prisma"),
	"utf8",
);
const tenant = new Set<string>(TENANT_MODELS);

type Edge = {
	table: string;
	fk: string;
	parentTable: string;
	parentCol: string;
};
const tables = new Map<string, string>();
const edges: Edge[] = [];
const tableOf = (model: string): string => {
	const t = tables.get(model);
	if (!t) throw new Error(`unknown model ${model}`);
	return t;
};

for (const [, name, body] of schema.matchAll(
	/^model (\w+) \{\n([\s\S]*?)^\}/gm,
)) {
	const map = body.match(/@@map\("([^"]+)"\)/);
	tables.set(name, map?.[1] ?? name);
}
for (const [, name, body] of schema.matchAll(
	/^model (\w+) \{\n([\s\S]*?)^\}/gm,
)) {
	if (!tenant.has(name)) continue;
	for (const line of body.split("\n")) {
		const m = line
			.trim()
			.match(
				/^(\w+)\s+(\w+)\??\s+@relation\([^)]*fields:\s*\[([^\]]+)\][^)]*references:\s*\[([^\]]+)\]/,
			);
		if (!m) continue;
		const [, , target, fields, refs] = m;
		if (!target || !tenant.has(target)) continue;
		const fks = (fields ?? "").split(",").map((x) => x.trim());
		const rs = (refs ?? "").split(",").map((x) => x.trim());
		if (fks.length !== 1 || rs.length !== 1 || fks[0] === "organizationId")
			continue;
		edges.push({
			table: tableOf(name),
			fk: fks[0] as string,
			parentTable: tableOf(target),
			parentCol: rs[0] as string,
		});
	}
}

const out: string[] = [];
out.push(`-- Same-organization foreign keys (generated by packages/db/scripts/generate-same-org-triggers.ts)
CREATE OR REPLACE FUNCTION crm_assert_same_org() RETURNS trigger AS $$
DECLARE
  fk_col text := TG_ARGV[0];
  parent_table text := TG_ARGV[1];
  parent_col text := TG_ARGV[2];
  fk_val text;
  parent_org text;
BEGIN
  EXECUTE format('SELECT ($1).%I::text', fk_col) INTO fk_val USING NEW;
  IF fk_val IS NULL THEN
    RETURN NEW;
  END IF;
  EXECUTE format('SELECT "organizationId" FROM %I WHERE %I = $1', parent_table, parent_col) INTO parent_org USING fk_val;
  IF parent_org IS NULL OR parent_org <> NEW."organizationId" THEN
    RAISE EXCEPTION 'cross-tenant reference: %.% = % belongs to organization % (row is in %)',
      TG_TABLE_NAME, fk_col, fk_val, COALESCE(parent_org, '<missing>'), NEW."organizationId"
      USING ERRCODE = '23503';
  END IF;
  RETURN NEW;
END
$$ LANGUAGE plpgsql;

-- A tenant row never changes organization.
CREATE OR REPLACE FUNCTION crm_org_immutable() RETURNS trigger AS $$
BEGIN
  RAISE EXCEPTION 'organizationId is immutable: %.% cannot move from % to %',
    TG_TABLE_NAME, 'organizationId', OLD."organizationId", NEW."organizationId"
    USING ERRCODE = '23514';
END
$$ LANGUAGE plpgsql;
`);
const tenantTables = [...new Set(TENANT_MODELS.map((m) => tableOf(m)))].sort();
for (const t of tenantTables) {
	const name = `${t}_org_immutable`;
	out.push(`DROP TRIGGER IF EXISTS "${name}" ON "${t}";
CREATE TRIGGER "${name}" BEFORE UPDATE OF "organizationId" ON "${t}"
  FOR EACH ROW WHEN (OLD."organizationId" IS DISTINCT FROM NEW."organizationId")
  EXECUTE FUNCTION crm_org_immutable();`);
}
for (const e of edges) {
	const name = `${e.table}_${e.fk}_same_org`;
	out.push(`DROP TRIGGER IF EXISTS "${name}" ON "${e.table}";
CREATE TRIGGER "${name}" BEFORE INSERT OR UPDATE OF "${e.fk}", "organizationId" ON "${e.table}"
  FOR EACH ROW EXECUTE FUNCTION crm_assert_same_org('${e.fk}', '${e.parentTable}', '${e.parentCol}');`);
}
out.push(
	`-- ${edges.length} tenant→tenant foreign keys guarded; organizationId immutable on ${tenantTables.length} tables`,
);
process.stdout.write(`${out.join("\n")}\n`);
